version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdevops
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network


  app-spring:
    depends_on:
      - mysqldb
    image: azizomri/springback-testdevops:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/testdevops?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - app-network

  app-angular:
    depends_on:
      - app-spring
    image: azizomri/angularfront-testdevops:latest
    restart: on-failure
    ports:
      - 4200:80
    networks:
      - app-network  

volumes:
  db:

networks:
  app-network:
    driver: bridge